name: Deploy Web App

on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: print env of PR target
        run: echo ${{github.event.pull_request.base.ref}}
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.1"
      
      - if: ${{github.event.pull_request.base.ref}} != "main"
        run: echo 1

      # - run: |
      #     if "${{github.event.pull_request.base.ref}}" == main 
      #     cd ${{github.event.pull_request.base.ref}}
      #     terraform init
      #   if: contains(fromJSON('["devel", "main", "staging"]'), github.event.pull_request.base.ref)

      # - run: terraform plan -no-color
      #   continue-on-error: true
