name: Deploy Web App

on:
  pull_request:
    branches:
    - main
    - staging
    - devel
  push:
    branches:
    - main
    - staging
    - devel

jobs:
  tf-plan-apply:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: print env of PR target
        run: echo ${{github.event.pull_request.base.ref}}
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.1"

      - name: Define tf path
        id: tf-path
        run: |
          if [ "${{github.event_name}}" == "pull_request" ]; then
            echo tf_path="${{github.event.pull_request.base.ref}}" >> $GITHUB_OUTPUT
            [ "${{github.event.pull_request.base.ref}}" == "main" ] && echo tf_path="prod" >> $GITHUB_OUTPUT
          fi
          if [ "${{github.event_name}}" == "pull" ]; then
            echo tf_path="${{github.ref_name}}" >> $GITHUB_OUTPUT
            [ "${{github.ref_name}}" == "main" ] && echo tf_path="prod" >> $GITHUB_OUTPUT
          fi

      - name: Terraform fmt
        id: fmt
        if: ${{github.event_name}} == 'pull_request'
        working-directory: ${{steps.tf-path.outputs.tf_path}}
        run: |
          terraform fmt -check
      
      - id: init
        working-directory: ${{steps.tf-path.outputs.tf_path}}
        run: |
          terraform init

      - name: Terraform Validate
        if: ${{github.event_name}} == 'pull_request'
        id: validate
        working-directory: ${{steps.tf-path.outputs.tf_path}}
        run: |
          terraform validate -no-color
        
      - name: Terraform Plan
        id: plan
        if: ${{github.event_name}} == 'pull_request'
        env:
          TF_VAR_gcp_env: ${{steps.tf-path.outputs.tf_path}}
        working-directory: ${{steps.tf-path.outputs.tf_path}}
        run: |
          terraform plan -no-color

      - name: Terraform Apply
        id: apply
        if: ${{github.event_name}} == 'push'
        env:
          TF_VAR_gcp_env: ${{steps.tf-path.outputs.tf_path}}
        working-directory: ${{steps.tf-path.outputs.tf_path}}
        run: |
          terraform apply -auto-approve
