name: Deploy Web App

on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: print env of PR target
        run: echo ${{github.event.pull_request.base.ref}}
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.1"

      - id: set-vars
        run: |
          [ "${{github.event.pull_request.base.ref}}" == "devel" ] && echo tf_path=devel >> $GITHUB_OUTPUT
          [ "${{github.event.pull_request.base.ref}}" == "staging" ] && echo tf_path=staging >> $GITHUB_OUTPUT
          [ "${{github.event.pull_request.base.ref}}" == "main" ] && echo tf_path=prod >> $GITHUB_OUTPUT
          [ "${{github.event.pull_request.base.ref}}" == "master" ] && echo tf_path=prod >> $GITHUB_OUTPUT
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      
      
          
      - id: init
        run: |
          cd ${{steps.set-vars.outputs.tf_path}}
          terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
        
      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>
      
            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`
      
            </details>
      
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
      
            <details><summary>Show Plan</summary>
      
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
      
            </details>
      
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
      
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
