name: Deploy Web App

on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: print env of PR target
        run: echo ${{github.event.pull_request.base.ref}}
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.1"

      - run: 

      - run: |
          [ "${{github.event.pull_request.base.ref}}" == "devel" ] && cd devel
          [ "${{github.event.pull_request.base.ref}}" == "staging" ] && cd staging
          [ "${{github.event.pull_request.base.ref}}" == "main" ] && cd prod
          [ "${{github.event.pull_request.base.ref}}" == "master" ] && cd prod
          pwd
          terraform init

      - run: pwd
