name: Deploy Web App

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login Artifact
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS }}
       

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
            push: true
            tags: us-central1-docker.pkg.dev/core-1s4u/ght/any_image:1403
